project:
  type: website
  output-dir: docs

website:
  title: "My First Quarto Blog"
  description: "A blog about multibody dynamics"
  navbar:
    pinned: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  page-footer:
    center: 
      - text: "About"
        href: about.qmd
format:
  html:
    theme:
      - minty
    css: styles.css



